inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - db/*
    - db/migrate/*
    - bin/*
    - tmp/*

Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_*.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/services/*.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'Gemfile'

Style/SymbolArray:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude: 
    - 'config/puma.rb'

Style/GlobalStdStream:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
