inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - db/*
    - db/migrate/*
    - bin/*
Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_*.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/SymbolArray:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude: 
    - 'config/puma.rb'

Style/GlobalStdStream:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*.rb'
# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 13

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 9

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

