# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
_default: &_default
  adapter: postgresql
  encoding: unicode
  reconnect: true
  prepared_statements: true
  # schema_search_path: "public"
  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= (defined?(Sidekiq) && Sidekiq.server?) ? Sidekiq.instance_variable_get('@config').concurrency : (ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i * ENV.fetch('WEB_CONCURRENCY') { 1 }.to_i) %>
  <% if ENV.key?('SAMOCHAT_DATABASE_HOST') %>
  host: <%= ENV.fetch('SAMOCHAT_DATABASE_HOST') %>
  <% end %>
  <% if ENV.key?('SAMOCHAT_DATABASE_USERNAME') %>
  username: <%= ENV['SAMOCHAT_DATABASE_USERNAME'] %>
  <% end %>
  <% if ENV.key?('SAMOCHAT_DATABASE_PASSWORD') %>
  password: <%= ENV["SAMOCHAT_DATABASE_PASSWORD"] %>
  <% end %>
  <% if ENV.key?('SAMOCHAT_DATABASE_URL') %>
  url: <%= ENV['SAMOCHAT_DATABASE_URL'] %>
  <% end %>

  size_estimate_samples: 1000
  store_options: &default_store_options
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>

development:
  primary: &development
    <<: *_default
    database: samochat_development
  cache:
    <<: *development
    database: samochat_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *development
    database: samochat_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *development
    database: samochat_development_cable
    migrations_paths: db/cable_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *_default
  database: samochat_test

production:
  primary: &production
    <<: *_default
    database: <%= ENV.fetch( 'SAMOCHAT_DATABASE_NAME', 'samochat_production' ) %>
    migrations_paths: db/migrate
  cache:
    <<: *production
    database: samochat_production_cache
    migrations_paths: db/cache_migrate
    store_options:
      <<: *default_store_options
      max_entries: <%= Integer(ENV.fetch('SOLID_CACHE_MAX_ENTRIES_GB','4')).gigabytes %>
  queue:
    <<: *production
    database: samochat_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *production
    database: samochat_production_cable
    migrations_paths: db/cable_migrate
