name: Deploy
run-name: Deploy to production by @${{ github.actor }}
concurrency: production
on:
  push:
    branches: [ production ]
  workflow_run:
    workflows: [Test, Rubocop, Brakeman & bundler-audit]
    branches: [$default-branch]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: ./bin/cap production deploy
